var vn_server_widget="http://widget.voxnucleus.fr",vn_server="http://www.voxnucleus.fr",vn_server_api=vn_server_widget+"/getinformation",vn_share_url=vn_server+"/postmanagement/sharer",vn_vote_url=vn_server+"/request/popup/votepopup?postId=",vn_post_base=vn_server+"/post/",vn_small_logo_widget=vn_server+"/image/website/widget/vn_small_widget.png",vn_small_logo_widget_c=vn_server+"/image/website/widget/vn_small_widget_clicked.png",button_handler,gathered_data,getElementsByClassName=function(a,b,c){getElementsByClassName=
document.getElementsByClassName?function(g,d,e){e=e||document;g=e.getElementsByClassName(g);d=d?RegExp("\\b"+d+"\\b","i"):null;e=[];for(var h,f=0,i=g.length;f<i;f+=1){h=g[f];if(!d||d.test(h.nodeName))e.push(h)}return e}:document.evaluate?function(g,d,e){d=d||"*";e=e||document;var h=g.split(" "),f="",i=document.documentElement.namespaceURI==="http://www.w3.org/1999/xhtml"?"http://www.w3.org/1999/xhtml":null;g=[];for(var k,j=0,l=h.length;j<l;j+=1)f+="[contains(concat(' ', @class, ' '), ' "+h[j]+" ')]";
try{k=document.evaluate(".//"+d+f,e,i,0,null)}catch(m){k=document.evaluate(".//"+d+f,e,null,0,null)}for(;d=k.iterateNext();)g.push(d);return g}:function(g,d,e){d=d||"*";e=e||document;var h=g.split(" ");g=[];d=d==="*"&&e.all?e.all:e.getElementsByTagName(d);e=[];var f;f=0;for(var i=h.length;f<i;f+=1)g.push(RegExp("(^|\\s)"+h[f]+"(\\s|$)"));i=0;for(var k=d.length;i<k;i+=1){h=d[i];f=false;for(var j=0,l=g.length;j<l;j+=1){f=g[j].test(h.className);if(!f)break}f&&e.push(h)}return e};return getElementsByClassName(a,
b,c)};onload=function(){callvoxnucleus(vn_server_api,"","","postId")};function callvoxnucleus(a){if(getElementsByClassName("vn_button").length>0){button_handler=getElementsByClassName("vn_button")[0];a=addGetParam("buttontype","icone",a);gathered_data=gather_data(button_handler);a=addGetParam("wherefrom",gathered_data.url,a);var b=document.createElement("script");b.async=true;b.setAttribute("src",a);b.setAttribute("type","text/javascript");document.body.appendChild(b)}}
function displayButtons(a){a=createButton(a);button_handler.appendChild(a);clean_data(button_handler)}function createButton(a){var b=document.createElement("div");b.style.width=10;b.style.height=30;b.appendChild(insert_small_image(a.isInDatabase,create_link_from_data(a)));return b}
function insert_small_image(a,b){var c=document.createElement("img");c.src=vn_small_logo_widget;c.style.cursor="pointer";c.onclick=function(){a?window.open(b,"test","height=300,width=810,scrollbars=yes"):window.open(b)};return c}
function create_link_from_data(a){if(a.isInDatabase)return vn_vote_url+a.postId;else{a=gather_data(button_handler);var b=vn_share_url;b=addGetParam("link",encodeURI(a.url),b);if(a.title)b=addGetParam("title",encodeURI(a.title),b);if(a.description)b=addGetParam("description",encodeURI(a.description),b);if(a.tags)b=addGetParam("tags",encodeURI(a.tags),b);return b}}
function gather_data(a){var b={},c=getElementsByClassName("vn_description",a);b.description=c.length>0?c[0].firstChild.data:"";c=getElementsByClassName("vn_title",a);b.title=c.length>0?c[0].firstChild.data:document.title;c=getElementsByClassName("vn_tags",a);b.tags=c.length>0?c[0].firstChild.data:"";a=getElementsByClassName("vn_link",a);b.url=a.length>0?encodeURIComponent(a[0].firstChild.data):encodeURIComponent(document.location.href);return b}
function clean_data(a){for(var b=getElementsByClassName("vn_data",a),c=0;c<b.length;c++)a.removeChild(toDel=b[c])}function addGetParam(a,b,c){c+=c.indexOf("?")>-1?"&"+a+"="+b:"?"+a+"="+b;return c};
